spring:
  application:
    name: example-springcloud-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: example-springcloud-config-server
      profile: master
#      uri: http://127.0.0.1:8888

server:
  port: 8771

management:
  context-path: /actuator

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true

