spring:
  application:
    name: example-springcloud-service

server:
  port: 8771

management:
  context-path: /actuator

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

