spring:
  application:
    name: eureka-server
server:
  port: 8761


eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka-server}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
