spring:
  application:
    name: example-springcloud-register
server:
  port: 8761


eureka:
  instance:
    hostname: register.xiayong.me
  client:
    register-with-eureka: false
    fetch-registry: false 



---
spring:
  profiles: register-1

eureka:
  instance:
    hostname: register1.xiayong.me
  client:
    serviceUrl:
      defaultZone: http://register2.xiayong.me:${server.port}/eureka/

---
spring:
  profiles: register-2

eureka:
  instance:
    hostname: register2.xiayong.me
  client:
    serviceUrl:
      defaultZone: http://register1.xiayong.me:${server.port}/eureka/

