spring:
  application:
    name: example-springcloud-register
server:
  port: 8761


eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: register.xiayong.me
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false



---
spring:
  profiles: register-1

eureka:
  instance:
    hostname: register1.xiayong.me
  client:
    serviceUrl:
      defaultZone: http://register2.xiayong.me:${server.port}/eureka/

---
spring:
  profiles: register-2

eureka:
  instance:
    hostname: register2.xiayong.me
  client:
    serviceUrl:
      defaultZone: http://register1.xiayong.me:${server.port}/eureka/

