spring:
  application:
    name: example-springcloud-register-server

---
spring:
  profiles: node1
server:
  port: 8761

eureka:
  instance:
    hostname: node1
  client:
    serviceUrl:
      defaultZone: http://node2:8762/eureka/

---
spring:
  profiles: node2
server:
  port: 8762

eureka:
  instance:
    hostname: node2
  client:
    serviceUrl:
      defaultZone: http://node1:8761/eureka/

