spring:
  application:
    name: example-springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiayong/config

server:
  port: 8771

management:
  context-path: /actuator

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true



