spring:
  application:
    name: example-springcloud-consumer

server:
  port: 8781

management:
  context-path: /actuator

eureka:
  client:
    serviceUrl:
      defaultZone: http://node1:8761/eureka/,http://node2:8762/eureka/
  instance:
      statusPageUrlPath: ${management.context-path}/info
      healthCheckUrlPath: ${management.context-path}/health