spring:
  application:
    name: example-springcloud-consumer

server:
  port: 8781

management:
  context-path: /actuator

eureka:
  client:
    serviceUrl:
      defaultZone: http://register1.xiayong.me:8761/eureka/,http://register2.xiayong.me:8761/eureka/
  instance:
    preferIpAddress: true
