spring:
  application:
    name: example-springcloud-consumer

server:
  port: 8781

management:
  context-path: /actuator

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
